### ISSUE TITLE
can't find end of central directory

### ISSUE THREAD

**Issue by wlpeter** [SheetJS/js-xlsx#1013]
I upload one file which had about ten thousand lines of text, but it throw error. The error is "can't find end of central directory".

```
ERROR 24471 nodejs.Error: Corrupted zip : can't find end of central directory (uncaughtException throw 1 times on pid:24471)
    at ZipEntries.readEndOfCentral (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/jszip.js:2270:19)
    at ZipEntries.load (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/jszip.js:2332:14)
    at new ZipEntries (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/jszip.js:2156:14)
    at JSZip.module.exports [as load] (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/jszip.js:577:18)
    at new JSZip (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/jszip.js:524:14)
    at read_zip (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/xlsx.js:18863:24)
    at Object.readSync [as read] (/home/servers/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/xlsx.js:18931:69)
    at FileStream.stream.once (/home/servers/api.cloud.nh/app/extend/application.js:200:22)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at FileStream.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by SheetJSDev** [comment]
@wlpeter This is reproducible with leading characters `PK` followed by two tab characters:

```js
require('xlsx').read("PK\t\t123", {type:"binary"})
```

The fix is in `bits/87_read.js`:

```diff
-               case 0x50: if(n[1] === 0x4B && n[2] < 0x20 && n[3] < 0x20) return read_zip(d, o); break;
+               case 0x50: return (n[1] === 0x4B && n[2] < 0x09 && n[3] < 0x09) ? read_zip(d, o) : read_prn(data, d, o, str); break;
```

**Comment by superlbr** [comment]
Well, repeated again with npm package xlsx (version 0.12.4)
```
nodejs.Error: Corrupted zip : can't find end of central directory
    at ZipEntries.readEndOfCentral (/opt/tuhuo/api/node_modules/xlsx/jszip.js:2273:19)
    at ZipEntries.load (/opt/tuhuo/api/node_modules/xlsx/jszip.js:2335:14)
    at new ZipEntries (/opt/tuhuo/api/node_modules/xlsx/jszip.js:2159:14)
    at JSZipSync.module.exports [as load] (/opt/tuhuo/api/node_modules/xlsx/jszip.js:580:18)
    at new JSZipSync (/opt/tuhuo/api/node_modules/xlsx/jszip.js:527:14)
    at read_zip (/opt/tuhuo/api/node_modules/xlsx/xlsx.js:19192:24)
    at readSync (/opt/tuhuo/api/node_modules/xlsx/xlsx.js:19260:69)
    at Object.readFileSync (/opt/tuhuo/api/node_modules/xlsx/xlsx.js:19274:9)
    at Object.parse (/opt/tuhuo/api/node_modules/node-xlsx/src/index.js:7:21)
```

**Comment by reviewher** [comment]
@superlbr can you upload a file ?

**Comment by superlbr** [comment]
[城市经典高迪0427的副本.xlsx](https://github.com/SheetJS/js-xlsx/files/1953721/0427.xlsx)

**Comment by rushglen** [comment]
Got this error using SZip v3.2.1 when using **jszip.min.js**

> Can't find end of central directory : is this a zip file ? If it is, see 
> 
> https://stuk.github.io/jszip/documentation/howto/read_zip.html

If I use **jszip.js** (not minified version) it works!

**Comment by idubi** [comment]
`workbook.xlsx.readFile`      .....   will try to load xlsx file 

that is a compressed excel file 
so it will fail with this message : 

`_stack:'Error: Can't find end of central directory_ `

if you want to load a csv file you need to use :` _workbook.csv.readFile_` 
if you want a regular excel (uncompressed) then :  `_workbook.excel.readFile_`
