### ISSUE TITLE
nodejs.TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by wlpeter** [SheetJS/js-xlsx#1014]
I upload one file which had about ten thousand lines of text, but it throw error. The error is "nodejs.TypeError: Cannot read property '0' of null".

```
2018-03-02 15:10:27,522 ERROR 9073 nodejs.TypeError: Cannot read property '0' of null (uncaughtException throw 1 times on pid:9073)
    at firstbyte (/root/workspace/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/xlsx.js:18842:27)
    at Object.readSync [as read] (/root/workspace/api.cloud.nh/node_modules/_xlsx@0.11.19@xlsx/xlsx.js:18925:14)
    at FileStream.stream.once (/root/workspace/api.cloud.nh/app/extend/application.js:200:22)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at FileStream.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

pid: 9073
hostname: ubuntu

```

**Comment by wlpeter** [comment]
my mistake, sorry

**Comment by caub** [comment]
What was your mistake? I've the same error
