### ISSUE TITLE
shange SheetNames value

### ISSUE THREAD

**Issue by zp29** [SheetJS/js-xlsx#1068]
this is Code
```javascript
const wb = XLSX.readFile('data.xls')
wb.SheetNames[0] = 'Sheet1'
console.log( wb.SheetNames[0] )
XLSX.writeFile(wb, 'NewData.xls')
```

this is error
```bash
Sheet1
TypeError: Cannot read property 'length' of undefined
    at safe_decode_range (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:2772:
18)
    at write_FEAT (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:17606:14)
    at write_ws_biff8 (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:17696:9)
    at write_biff8_buf (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:17791:6
8)
    at write_biff_buf (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:17799:26)
    at write_xlscfb (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:16223:33)
    at write_cfb_type (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:19290:12)
    at writeSync (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:19372:46)
    at Object.writeFileSync (F:\work\ccdata\test\y3\node_modules\xlsx\xlsx.js:19
400:9)
    at filterXls (F:\work\ccdata\test\y3\app.js:141:8)
```
I want to change `SheetNames` value
How to solve？please！

**Comment by SheetJSDev** [comment]
You need to change both `Sheets` and `SheetNames`:

```js
var old_name = wb.SheetNames[0], new_name = 'Sheet1'
const wb = XLSX.readFile('data.xls')

/* change SheetNames */
wb.SheetNames[0] = new_name

/* change Sheets */
wb.Sheets[new_name] = wb.Sheets[old_name];
delete wb.Sheets[old_name];

/* write file */
XLSX.writeFile(wb, 'NewData.xls')
```

Here's a fiddle: https://jsfiddle.net/sheetjs/4zmrumt6/
