### ISSUE TITLE
Invalid HTML: could not find <table>

### ISSUE THREAD

**Issue by kaanbursa** [SheetJS/js-xlsx#1110]
Usually it does succedd but sometimes I get this error and it crashes any idea?

if(!mtch) throw new Error("Invalid HTML: could not find <table>");
		          ^

Error: Invalid HTML: could not find <table>
    at html_to_sheet (/.../node_modules/xlsx/xlsx.js:17000:19)
    at Object.html_to_book [as to_workbook] (/.../node_modules/xlsx/xlsx.js:17056:28)
    at parse_xlml_xml (/.../node_modules/xlsx/xlsx.js:13714:26)
    at parse_xlml (/.../node_modules/xlsx/xlsx.js:14362:53)
    at readSync (/../node_modules/xlsx/xlsx.js:18394:21)
    at Object.readFileSync (/.../node_modules/xlsx/xlsx.js:18412:9)
    at Request._callback (/.../server/routes/api.js:137:24)
    at Request.self.callback (/.../node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/.../node_modules/request/request.js:1163:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/.../node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by kaanbursa** [comment]
Hey,
It is an actual xlsm file which it converts sometime but it crashes sometime. Sorry the file is confidential cannot share but it is a basic .xlsm file

**Comment by SheetJSDev** [comment]
If it's an actual XLSM file, it would start with `0x50 0x4B` ("PK") and would never trigger the error.  Given that you are using `request`, It's likely you are seeing bad data (e.g. doing a HTTP request and receiving an HTML payload with the 404 error).  Try wrapping XLSX.read in a callback and saving he data to a file -- likely its an HTML error page.

**Comment by MedinaGitHub** [comment]
The same thing happens to me and in the registry of the console everything looks very good, but throws the same error

**Comment by MedinaGitHub** [comment]
I found the error! in rectJS the file xlsx must be in the 'public' folder

**Comment by samy-n** [comment]
> 
> 
> I found the error! in rectJS the file xlsx must be in the 'public' folder

This worked for me too

**Comment by Alexandria** [comment]
> I found the error! in rectJS the file xlsx must be in the 'public' folder

Working on a React App and putting my xlsx file in the `public` folder worked for me too.
