### ISSUE TITLE
Error when sheet has +197 rows

### ISSUE THREAD

**Issue by LucianoHanna** [SheetJS/js-xlsx#1321]
Getting this error when use XLSX.utils.sheet_to_json with sheet having +197 rows

(node:990) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
(node:990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 807)

Any idea why that?

**Comment by LucianoHanna** [comment]
Sorry, it was a problem on other dependency
