### ISSUE TITLE
unrecognized <xr:revisionPtr in workbook

### ISSUE THREAD

**Issue by janiskulj** [SheetJS/js-xlsx#1360]
When trying to parse excel files created by updatd Office 365 Excel i'm getting this error: 

"unrecognized <xr:revisionPtr in workbook"

Code line throving exception: 
var wb = XLSX.read(e.data.data, { type: 'base64', WTF: true });

Call Stack:
"Error: unrecognized <xr:revisionPtr in workbook
    at xml_wb (/xlsx.full.min.js:19:28759)
    at String.replace (<anonymous>)
    at parse_wb_xml (/xlsx.full.min.js:19:26058)
    at parse_wb (/xlsx.full.min.js:20:3387)
    at parse_zip (/xlsx.full.min.js:23:31680)
    at read_zip (/xlsx.full.min.js:24:7352)
    at Object.readSync [as read] (/xlsx.full.min.js:24:8161)

Any suggestions?

**Comment by reviewher** [comment]
As a stopgap, you can turn off WTF mode:

    var wb = XLSX.read(e.data.data, { type: 'base64' });
