### ISSUE TITLE
Parsing crashes on browser (array input type)

### ISSUE THREAD

**Issue by gcharp** [SheetJS/js-xlsx#1472]
Hi,
I am parsing a file on the browser via the array type. I am hoping to support .csv, .xlsx, and .xls filetypes. I also need to support IE 11.
```
//'data' comes from FileReader.readAsArrayBuffer
let dataU8 = new Uint8Array(data);
let workbook = XLSX.read(dataU8, {type: 'array', raw: true});
```
I'm getting various errors with different combinations of js-XLSX builds, filetype, and browser.

- Using xlsx.core.min.js on Chrome works for all three filetypes.
- Using xlsx.js on Chrome works for .xls and .csv, but on .xlsx gives the following error:
```
TypeError: jszip is not a constructor
    at read_zip (xlsx.js:20266)
    at readSync (xlsx.js:20335)
    at Object.readSync [as read] (xlsx.js:20315)
```
- Using xlsx.core.min.js on IE 11 works for .xlsx and .csv, but .xls gives the following error: 
```
TypeError: Object doesn't support property or method 'slice'
   at o (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.core.min.js:5:16599)
   at T (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.core.min.js:5:20934)
   at gm (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.core.min.js:16:23896)
   at gm (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.core.min.js:16:23354)
```
- Using xlsx.js on IE 11 works for .csv, but fails on both .xls and .xlsx. Error for .xls:
```
TypeError: Object doesn't support property or method 'slice'
   at parse (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:1351:1)
   at read (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:1662:2)
   at readSync (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:20330:14)
   at readSync (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:20315:72)
```
Error for .xlsx:
```
TypeError: Object doesn't support this action
   at read_zip (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:20266:32)
   at readSync (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:20335:14)
   at readSync (https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.js:20315:72)
```

**Comment by SheetJSDev** [comment]
You will need to include the shim first.  See http://oss.sheetjs.com/js-xlsx/ for an example:

```html
<script src="shim.js"></script>
<script src="xlsx.full.min.js"></script>
```
