### ISSUE TITLE
Cannot read property '0' of undefined when trying to read

### ISSUE THREAD

**Issue by PedramMarandi** [SheetJS/js-xlsx#1534]
Hello Everyone

I am downloading an Excel file from UR.  I have tried pass types Buffer array and Base64 to the library but regardless I get the below error.

```ypeError: Cannot read property '0' of undefined
    at parse_xlml_xml (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/xlsx.js:15599:32)
    at parse_xlml (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/xlsx.js:15981:25)
    at Object.readSync [as read] (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/xlsx.js:20332:21)
    at read (/Users/pedromarandi/projects/replenishment/src/lib/sheetUtils.js:25:15)
    at _callee$ (/Users/pedromarandi/projects/replenishment/src/lib/validations/purchaseOrderFileDetails.js:22:29)
    at tryCatch (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is how I read the file
`javascript
export function toSheet(fileContent) {
  return XLSX.read(fileContent, { type: 'base64' }); // I have also tried no type, array and buffer
}
`

The thing is it is not happening for all of the files. I have also prepared an [example](https://www.dropbox.com/s/vs4dj244hk0by8r/1111111.xlsx?dl=0)

**Comment by SheetJSDev** [comment]
You can explicitly test that the file by itself is not causing issues: drag and drop that file in http://oss.sheetjs.com/ .

That particular error shows up when you are passing what appears to be an HTML or XML document that has no tables.  In context, you're probably getting a standard 404 page in response.  You should add a check in your application to confirm that the response is successful.

**Comment by bobrosoft** [comment]
I hope that will help to somebody: 
I had the same issue because I was reading file with FileReader.readAsText method. Also, even if some XLS file worked, I was getting some broken characters output like as there was wrong encoding or GZIP compression. You should use FileReader.readAsArrayBuffer method to read the file, see "Browser drag-and-drop" example there https://github.com/SheetJS/sheetjs#parsing-workbooks

**Comment by SheetJSDev** [comment]
@bobrosoft can you stick a note in https://github.com/SheetJS/sheetjs/wiki/Browser-Errors (add a subsection with the error text as header and a comment about avoiding `readAsText` in the body)?

**Comment by bobrosoft** [comment]
@SheetJSDev done 👍 https://github.com/SheetJS/sheetjs/wiki/Browser-Errors#error-cannot-read-property-0-of-undefined
