### ISSUE TITLE
writeExcel TypeError: Cannot read property 'texts' of undefined

### ISSUE THREAD

**Issue by Florian007** [SheetJS/js-xlsx#1541]
Hi, I am using
"exceljs": "^1.12.1",
"xlsx": "^0.14.3"
After cloning and saving an Excel .xlsx file with following code

`let newWorkbook: Excel.Workbook = new Excel.Workbook()
    const workbook: Excel.Workbook = new Excel.Workbook()
    await workbook.xlsx.readFile(sourceFilePath)
    newWorkbook.views = workbook.views
    newWorkbook.model = workbook.model
await newWorkbook.xlsx.writeFile(writeFilePath)`

I got the error:

`writeExcel err: TypeError: Cannot read property 'texts' of undefined
    at module.exports.render (/Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xform/comment/comment-xform.js:64:20)
    at /Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xform/comment/comments-xform.js:36:25
    at Array.forEach (<anonymous>)
    at module.exports.render (/Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xform/comment/comments-xform.js:35:20)
    at /Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xlsx.js:637:25
    at Array.forEach (<anonymous>)
    at /Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xlsx.js:620:24
    at new Promise (<anonymous>)
    at module.exports.addWorksheets (/Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xlsx.js:613:12)
    at /Users/xxx/Documents/node/excelParser/node_modules/.registry.npmjs.org/exceljs/1.12.1/node_modules/exceljs/dist/es5/xlsx/xlsx.js:707:21`

Changing the line 64 in "comment-xform.js" from
`if (model.note.texts) {`
to
`if (model.note && model.note.texts) {`
fixed the issue.

Thanks for the awesome work!

**Comment by SheetJSDev** [comment]
You probably meant to report to https://github.com/exceljs/exceljs
