### ISSUE TITLE
Error when trying to read .xls file

### ISSUE THREAD

**Issue by rtm619** [SheetJS/js-xlsx#1589]
Hi,

I am trying to read and convert some .xls file to JSON but I am repeatedly getting this error: 

```
 TypeError: Cannot set property length of [object Object] which has only a getter
    at sbcs_d (D:\Workspace\Import-Scripts\node_modules\xlsx-to-json\node_modules\xlsx\dist\cpexcel.js:906:20)
    at Object.decode (D:\Workspace\Import-Scripts\node_modules\xlsx-to-json\node_modules\xlsx\dist\cpexcel.js:1191:40)
    at __lpstr (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:3203:90)
    at Buffer.ReadShift [as read_shift] (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:3236:26)
    at parse_compobj (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:16372:21)
    at parse_xlscfb (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:17287:13)
    at read_cfb (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:20338:9)
    at Object.readSync [as read] (D:\Workspace\Import-Scripts\node_modules\xlsx\xlsx.js:20406:21)
```
My code is as follows:

```
const XLSX = require("xlsx");

async function generateJSONfromXLS(filePath) {
    const workbook = XLSX.readFile(filePath);
}

module.exports = generateJSONfromXLS;
```

Here, filepath is something like this: './files/excel1.xls'

Is there something I am doing incorrectly here?

TIA

**Comment by reviewher** [comment]
Since this is coming as a dependency of `xlsx-to-json`, you might be running an older version.  Can you see what version you are currently using?  You might need to check `npm ls`

**Comment by jessrosenfield** [comment]
Can this issue be reopened? I'm getting this error when processing `xls` files:
```
TypeError: Cannot set property length of [object Object] which has only a getter
    at sbcs_d (/var/task/node_modules/harb/dist/cpexcel.js:906:20)
    at Object.decode (/var/task/node_modules/harb/dist/cpexcel.js:1191:40)
    at __lpstr (/var/task/node_modules/xlsx/xlsx.js:3333:90)
    at Array.ReadShift [as read_shift] (/var/task/node_modules/xlsx/xlsx.js:3366:26)
    at parse_compobj (/var/task/node_modules/xlsx/xlsx.js:16827:21)
    at parse_xlscfb (/var/task/node_modules/xlsx/xlsx.js:17744:13)
    at read_cfb (/var/task/node_modules/xlsx/xlsx.js:20885:9)
    at readSync (/var/task/node_modules/xlsx/xlsx.js:20954:21)
    at Object.readSync [as read] (/var/task/node_modules/xlsx/xlsx.js:20938:79)
```


Node: v10.19.0
```
└─┬ xlsx@0.16.3
  ├─┬ adler-32@1.2.0
  │ ├── exit-on-epipe@1.0.1 deduped
  │ └── printj@1.1.2
  ├─┬ cfb@1.1.4
  │ ├── adler-32@1.2.0 deduped
  │ ├── commander@2.17.1 deduped
  │ ├── crc-32@1.2.0 deduped
  │ └── printj@1.1.2 deduped
  ├─┬ codepage@1.14.0
  │ ├── commander@2.14.1
  │ └── exit-on-epipe@1.0.1 deduped
  ├── commander@2.17.1
  ├─┬ crc-32@1.2.0
  │ ├── exit-on-epipe@1.0.1 deduped
  │ └── printj@1.1.2 deduped
  ├── exit-on-epipe@1.0.1
  ├─┬ ssf@0.11.2
  │ └── frac@1.1.2
  ├── wmf@1.0.2
  └── word@0.3.0
```

I didn't see anything regarding `0.16.3` and `0.16.4` in the [CHANGELOG](https://github.com/SheetJS/sheetjs/blob/master/CHANGELOG.md)  so I'm assuming this still would hold for the very recent release of `0.16.4`.

**Comment by SheetJSDev** [comment]
That error suggests you are somehow still using a very old version of the library.  Can you check if `harb` is installed?  If it is, please remove and try again (It was a relic from a time when the plaintext stuff was not part of the main repo).

To be sure it isn't affecting the latest version, please test against https://oss.sheetjs.com/ (click and drag into the box)

**Comment by jessrosenfield** [comment]
@SheetJSDev Thanks for responding! While I'm using the latest version, I've determined my issue is due to conflicting dependencies from [textract](https://www.npmjs.com/package/textract), a package I'm using for other file types (https://github.com/dbashford/textract/issues/186).

**Comment by jessrosenfield** [comment]
The file worked fine when using https://oss.sheet.js.com/

**Comment by SheetJSDev** [comment]
textract was using "j" because of a historical organization issue: in the past, the xls and xlsx components were separate.  Now they are unified under the "xlsx" module on npm, so textract should switch over.  I left a comment on the linked textract issue.

**Comment by jessrosenfield** [comment]
@SheetJSDev is there a way to prevent dependencies from other packages silently conflicting with `xlsx` behavior? It seems like either `harb` should not be called by the latest package, or the latest package should warn or error if this unintended behavior occurs.
