### ISSUE TITLE
readFile() retrurns empty row results. with a sheet "!margin" property being populated only.

### ISSUE THREAD

**Issue by samih-dev** [SheetJS/js-xlsx#1595]
Hi,
Thanks for exposing part of this module to all.

readFile() returns empty row results. with a sheet data containing the "!margin" property being populated only.

Please guide me how I can send the file privately? so you can test

Thanks
Samih

**Comment by SheetJSDev** [comment]
Send an email with an attachment or link to dev@sheetjs.com

**Comment by samih-dev** [comment]
sent an email, thanks.

**Comment by samih-dev** [comment]
Hi @SheetJSDev  

after removing and adding the new xlsx **0.15.1**, I got the following error now with the same file I sent: 

**Message:** 
unsupported format |#,0|

**Stack:** 
Error: unsupported format |#,0|
    at write_num_int (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:712:8)
    at write_num (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:715:27)
    at eval_fmt (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:916:11)
    at Object.format (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:1030:9)
    at safe_format (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:12833:18)
    at parse_ws_xml_data (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:13273:4)
    at parse_ws_xml (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:12909:11)
    at parse_ws (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:15138:9)
    at safe_parse_sheet (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:19993:25)
    at parse_zip (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:20123:3)
    at read_zip (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:20351:9)
    at readSync (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:20416:69)
    at Object.readFileSync (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\node_modules\xlsx\xlsx.js:20430:9)
    at Object.<anonymous> (c:\works\naden-tech\danny-struess\ds-treklin\ds-treklin-server-project\ds-treklin-server\dist\modules\misc\misc.api.js:58:35)
    at Generator.next (<anonymous>)

**Comment by samih-dev** [comment]
Hi @SheetJSDev

can you please check and reopen this issue?

Thanks 
Samih

**Comment by RunnableWeb** [comment]
Hi @SheetJSDev 
any updates?
