### ISSUE TITLE
demo is not working 

### ISSUE THREAD

**Issue by antonio-castellon** [SheetJS/js-xlsx#160]
Hi,

I try the demo http://oss.sheetjs.com/js-xlsx/ and it's fire an exception 
```
 Error: Corrupted zip : can't find end of central directory
    at Object.ZipEntries.readEndOfCentral (http://oss.sheetjs.com/js-xlsx/jszip.js:2087:27)
    at Object.ZipEntries.load (http://oss.sheetjs.com/js-xlsx/jszip.js:2104:18)
    at Object.ZipEntries (http://oss.sheetjs.com/js-xlsx/jszip.js:2010:18)
    at Object.JSZip.load (http://oss.sheetjs.com/js-xlsx/jszip.js:2115:22)
    at Object.JSZip (http://oss.sheetjs.com/js-xlsx/jszip.js:5:14)
    at Object.readSync [as read] (http://oss.sheetjs.com/js-xlsx/xlsx.js:5149:24)
    at DedicatedWorkerGlobalScope.onmessage (http://oss.sheetjs.com/js-xlsx/xlsxworker2.js:26:14)
xlsxworker2.js:18 Uncaught TypeError: Cannot read property 'length' of undefined
```

**Comment by SheetJSDev** [comment]
@antonio-castellon it looks like you didn't drop a non-password-protected XLSX/XLSB/XLSM/ODS file.  Can you check against http://oss.sheetjs.com/js-xls/ (this is for XLS)?  IF the issue still persists and if the file is not sensitive, I'd be glad to take a look -- shoot me a direct email (unfortunately github doesn't preserve attachments)

**Comment by antonio-castellon** [comment]
:-( 
```
undefined(index):120 worker.onmessage
xlsworker2.js:15 Uncaught TypeError: Cannot read property 'length' of undefined
```

**Comment by SheetJSDev** [comment]
@antonio-castellon What browser are you using?  Also, can you attach that file in an email to dev - at - sheetjs - dot - com so I could take a look?

**Comment by antonio-castellon** [comment]
Well, finally it was my mistake..I was using CSV file as an MSExcel file X-D ..sorry.
