### ISSUE TITLE
TypeError: Cannot read property 'readFileSync' of undefined

### ISSUE THREAD

**Issue by VikramTiwari** [SheetJS/js-xlsx#281]
I am trying to use js-xlsx on completion of an upload event. At the completion of upload i try to parse the file, which results in breaking the code.

Usage:
`var workbook = XLSX.readFile("file/path/filename.xlsx");`

Included file: `"bower_components/js-xlsx/dist/xlsx.core.min.js"`

```
```

**Comment by TheRobBrennan** [comment]
I'm getting the same thing, too. My code used to work fine reading files, but now I'm getting:

Importing ChalkSocial file import/20150810/myfile.xlsx
jszip/jszip.js:793
         result += String.fromCharCode(str.charCodeAt(i) & 0xff);
                                           ^
TypeError: undefined is not a function
    at Object.JSZip.utils.string2binary (jszip/jszip.js:793:44)
    at Object.StreamReader (jszip/jszip-load.js:61:36)
    at Object.ZipEntries.load (jszip/jszip-load.js:505:24)
    at Object.ZipEntries (jszip/jszip-load.js:341:15)
    at Object.JSZip.load (jszip/jszip-load.js:528:20)
    at Object.JSZip (jszip/jszip.js:38:12)
    at read_zip (/Users/rob/repos/adseek/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:11377:20)
    at readSync (/Users/rob/repos/adseek/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:11396:11)
    at Object.readFileSync (/Users/rob/repos/adseek/node_modules/node-xlsx/node_modules/xlsx/xlsx.js:11403:9)
    at Object.module.exports.parse (/Users/rob/repos/adseek/node_modules/node-xlsx/lib/node-xlsx.js:49:45)

**Comment by funkyLover** [comment]
I think , `readFileSync` is the nodejs method
and the method `XLSX.readFile()` base on the `readFileSync`
so you can't use `XLSX.readFile()` in browser side.

**Comment by SheetJSDev** [comment]
As @funkyLover pointed out, `readFile` is node only.  You need to grab the data in the browser and call `XLSX.read`.  [The README](https://github.com/SheetJS/js-xlsx#parsing-workbooks) includes some examples as well as links to demos showing how to read data on the client side.
