### ISSUE TITLE
can't read my file

### ISSUE THREAD

**Issue by ilaipi** [SheetJS/js-xlsx#341]
```
node initial/demo-prescription.xlsx 
/home/yyam/workspace/NCD/server/initial/demo-prescription.xlsx:1
(function (exports, require, module, __filename, __dirname) { PK
                                                                ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

my file:
[prescription.zip](https://github.com/SheetJS/js-xlsx/files/75883/prescription.zip)

**Comment by SaharZehavi** [comment]
having the same problem. solution anyone?

**Comment by reviewher** [comment]
You are trying to run an XLSX file in node.  Do you mean to run a script? I'm guessing you probably want to run something like 

```
$ node index.js initial/demo-prescription.xlsx 
```

The file itself works in the web demo as well as in the command line:

```
$ xlsx prescription.xlsx  --list-sheets
Sheet1
Sheet2
Sheet3
$ xlsx prescription.xlsx
Sheet1
pres_time,prescription_id,source_type,source,doctor_id,personal_id,,,
...
```
