### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by vineetl** [SheetJS/js-xlsx#419]
While doing a readFile for .xls file following error occurs. 

switch(state[state.length-1][0]) {
                                        ^

TypeError: Cannot read property '0' of undefined
    at parse_xlml_xml (/home/abc/node_modules/xlsx/xlsx.js:8815:32)
    at parse_xlml (/home/abc/node_modules/xlsx/xlsx.js:9171:53)
    at readSync (/home/abc/node_modules/xlsx/xlsx.js:11393:21)
    at Object.readFileSync (/home/abc/node_modules/xlsx/xlsx.js:11403:9)
    at Object.<anonymous> (/home/abc/readXL.js:2:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

please help me out

**Comment by chenvan** [comment]
I meet the same problem. I solve it by save the document again.

**Comment by SheetJSDev** [comment]
@vineetl @chenvan can you share a file that shows this problem?  I suspect those are really HTML files that happen to have the XLS extension, since that particular error and codepath mean the file started with a `<` (which the library guesses is a SpreadsheetML file)

**Comment by chenvan** [comment]
@SheetJSDev you guess is maybe right. My document is exported from a website which is about chinese stock markets.  Do you still want me to send you a copy? I don't know how to send to you? An email?

**Comment by SheetJSDev** [comment]
@chenvan You can send an email to dev@sheetjs.com

**Comment by SheetJSDev** [comment]
@chenvan received the file.  As I guessed, it was an HTML file.   This export is particularly interesting because of the number format hints in the style:

```html
<td style="text-align:right;mso-number-format:0.00;">
```

We'll keep this issue open until we decide how to handle HTML files.
