### ISSUE TITLE
Node 7 deprecation warning

### ISSUE THREAD

**Issue by IrishAdo** [SheetJS/js-xlsx#490]
(node:4119) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at utf8readc (/............../node_modules/xlsx/xlsx.js:1443:52)
    at make_xlsx (/............../node_modules/xlsx/xlsx.js:1444:25)
    at Object.<anonymous> (/............../node_modules/xlsx/xlsx.js:11653:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/............../node_modules/node-xlsx/lib/node-xlsx.js:3:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/............../node_modules/node-xlsx/index.js:1:80)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)

**Comment by IrishAdo** [comment]
Code added to fork and pull request generated

**Comment by reviewher** [comment]
@IrishAdo node initially added the deprecation warning in 7.0.0 but has removed it as of 7.3.0.
