### ISSUE TITLE
TypeError: _fs.writeFileSync is not a function

### ISSUE THREAD

**Issue by Ahmad19860** [SheetJS/js-xlsx#923]
Hi,
I am trying to create a sample excel file but i am getting error '_fs.writeFileSync is not a function'.
below is code to create the file-

```
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import * as XLSX from 'xlsx';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(platform: Platform) {
    platform.ready().then(() => {
      this.createSheet();
    });
  }

  ionViewDidLoad() {
  }

  createSheet() {
    var data = [
      [1, 2, 3],
      [true, false, null, "sheetjs"],
      ["foo    bar", "baz", new Date("2014-02-19T14:30Z"), "0.3"],
      ["baz", null, "\u0BEE", 3.14159],
      ["hidden"],
      ["visible"]
    ];

    var ws_name = "SheetJS";

    var wscols = [
      { wch: 6 }, // "characters"
      { wpx: 50 }, // "pixels"
      ,
      { hidden: true } // hide column
    ];

    /* At 96 PPI, 1 pt = 1 px */
    var wsrows = [
      { hpt: 12 }, // "points"
      { hpx: 16 }, // "pixels"
      ,
      { hpx: 24, level: 3 },
      { hidden: true }, // hide row
      { hidden: false }
    ];

    var wb = XLSX.utils.book_new();

    /* convert an array of arrays in JS to a CSF spreadsheet */
    var ws = XLSX.utils.aoa_to_sheet(data, { cellDates: true });
    XLSX.utils.book_append_sheet(wb, ws, ws_name);
    var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'binary' });
    console.log(wbout);
    XLSX.writeFile(wb, 'C:/Users/mahmad/Downloads/temp.xlsx', { bookSST: true, type: 'file' });
  }
}
```

This is my ionic info output:
```
@ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : D:\ANDROID_SDK

Misc:

    backend : pro
```

Below is the error-
```
ERROR Error: Uncaught (in promise): TypeError: _fs.writeFileSync is not a function
TypeError: _fs.writeFileSync is not a function
    at write_zip_type (file:///android_asset/www/build/vendor.js:139738:35)
    at writeSync (file:///android_asset/www/build/vendor.js:139830:22)
    at Object.writeFileSync (file:///android_asset/www/build/vendor.js:139853:9)
    at HomePage.webpackJsonp.195.HomePage.createSheet (file:///android_asset/www/build/main.js:98:56)
    at file:///android_asset/www/build/main.js:62:19
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.onInvoke (file:///android_asset/www/build/vendor.js:4982:33)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)
    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)
    at file:///android_asset/www/build/polyfills.js:3:20242
    at write_zip_type (file:///android_asset/www/build/vendor.js:139738:35)
    at writeSync (file:///android_asset/www/build/vendor.js:139830:22)
    at Object.writeFileSync (file:///android_asset/www/build/vendor.js:139853:9)
    at HomePage.webpackJsonp.195.HomePage.createSheet (file:///android_asset/www/build/main.js:98:56)
    at file:///android_asset/www/build/main.js:62:19
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.onInvoke (file:///android_asset/www/build/vendor.js:4982:33)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)
    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)
    at file:///android_asset/www/build/polyfills.js:3:20242
    at c (file:///android_asset/www/build/polyfills.js:3:19752)
    at file:///android_asset/www/build/polyfills.js:3:20273
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.onInvokeTask (file:///android_asset/www/build/vendor.js:4973:33)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
    at o (file:///android_asset/www/build/polyfills.js:3:7894)
    at e.invokeTask (file:///android_asset/www/build/polyfills.js:3:16823)
    at i.isUsingGlobalCallback.invoke (file:///android_asset/www/build/polyfills.js:3:16682)
    at n (file:///android_asset/www/build/polyfills.js:3:61)
```

Please help me to get out of this issue.

**Comment by SheetJSDev** [comment]
The `fs` module and `writeFile` only work in nodejs.  You need to use `write` to generate data and use an API to save to your device.

In the [`react-native`](https://github.com/SheetJS/js-xlsx/tree/master/demos/react#react-native) demo, the excellent [`react-native-fs`](https://www.npmjs.com/package/react-native-fs) library is used to write to file system.

For Ionic, it looks like [Ionic Native has a File library](https://ionicframework.com/docs/native/file/#writeFile) that can take a string.  Use the [`"binary"` or `"base64"` type in `XLSX.write`](https://docs.sheetjs.com/#output-type).

**Comment by reviewher** [comment]
For completeness sake, the [angular2 demo now includes an ionic example](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2#ionic) that reads from and writes to the documents directory of the device and displays an array of arrays as a grid.  

https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/ionic.ts is the code example.
