### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by fjmiaoxiao** [SheetJS/js-xlsx#978]
Hi there! Here's my problem.
My code is simple like: 
var XLSX = require('xlsx');
nothing else,  
but this error occurs:
ReferenceError: Blob is not defined
    at Object.<anonymous> (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:1494:28)
    at Object.17 (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:1511:4)
    at s (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:266)
    at c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:317
    at Object.13../base64 (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:631:15)
    at s (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:266)
    at c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:317
    at Object.9../base64 (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:536:19)
    at s (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:266)
    at e (c:\Program Files\nodejs\test\node_modules\xlsx\jszip.js:22:437)
I can use some help here,TKS

**Comment by reviewher** [comment]
Can't reproduce in node 0.8.28, 0.10.48, or 8.9.4 on windows 10 64-bit.  Try uninstalling and reinstalling node from the official packages.
